W7D3/MovieApp/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#                     bands GET    /bands(.:format)                                                                         bands#index
#                           POST   /bands(.:format)                                                                         bands#create
#                  new_band GET    /bands/new(.:format)                                                                     bands#new
#                 edit_band GET    /bands/:id/edit(.:format)                                                                bands#edit
#                      band GET    /bands/:id(.:format)                                                                     bands#show
#                           PATCH  /bands/:id(.:format)                                                                     bands#update
#                           PUT    /bands/:id(.:format)                                                                     bands#update
#                           DELETE /bands/:id(.:format)                                                                     bands#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :destroy, :update]
  resource :session, only: [:create, :destroy, :new]
end

W7D3/MovieApp/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: 'Album'
end

W7D3/MovieApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new, status: 422
        end
    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end

    def update
        @band = Band.find_by(id: params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url(@band.id)
        else
            flash.now[:errors] = @users.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find_by(id: params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params
            .require(:band)
            .permit(:name)
    end
end

W7D3/MovieApp/app/views/bands/edit.html.erb
<h2>Edit Your Band!</h2>
<form action="<%= band_url(@band.id) %>" method="post">
    <input type="hidden" name="_method" value="patch"/>
    <%= auth_token %>
    <label for="new_band_name">Band Name</label>
    <input type="text" id="new_band_name" name="band[name]" value="<%= @band.name %>"/>

    <input type="submit" value="Update Your Band!"/>
</form>

W7D3/MovieApp/app/views/bands/index.html.erb
<h2> All of the Bands </h2>
<br />
<a href="<%= new_band_url %>">Create a New Band</a>
<ul> 
    <% @bands.each do |band| %>
        <li><a href="<%= band_url(band.id) %>"><%= band.name %></a></li>
    <% end %>
</ul>


W7D3/MovieApp/app/views/bands/new.html.erb
<h2>Create a New Band!</h2>
<br />
<form action="<%= bands_url %>" method="post">
    <%= auth_token %>
    <label for="band_name">Band Name</label>
    <input type="text" id="band_name" name="band[name]"/>

    <input type="submit" value="Create New Band!"/>
</form>

W7D3/MovieApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<form action="<%= band_url(@band.id) %>" method="get"
    <input type="hidden" name="_method" value="delete"/>
    <%= auth_token %>
    <input type="submit" value="Delete This Band!"/>
    
    <br />
    <br />
    <a href="<%= new_band_album_url(@band.id) %>">Create an Album</a>
    <br />
    <br />
    <a href="<%= edit_band_url(@band.id) %>">Edit this Band</a>
    <br />
    <br />
    <a href="<%= bands_url %>">Back to the Bands Home Page</a>
</form>



<h2>All of my Albums</h2>
<ul> 
    <% @band.albums.each do |album| %>
        <li><a href="<%=album_url(album.id) %>"><%= album.title %></a></li>
    <% end %>
</ul>
