W7D3/MovieApp/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#                     bands GET    /bands(.:format)                                                                         bands#index
#                           POST   /bands(.:format)                                                                         bands#create
#                  new_band GET    /bands/new(.:format)                                                                     bands#new
#                 edit_band GET    /bands/:id/edit(.:format)                                                                bands#edit
#                      band GET    /bands/:id(.:format)                                                                     bands#show
#                           PATCH  /bands/:id(.:format)                                                                     bands#update
#                           PUT    /bands/:id(.:format)                                                                     bands#update
#                           DELETE /bands/:id(.:format)                                                                     bands#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :destroy, :update]
  resource :session, only: [:create, :destroy, :new]
end

W7D3/MovieApp/app/models/album.rb
class Album < ApplicationRecord
    validates :title, exclusion: { in: %w( Record record) }
    validates :band_id, uniqueness: { scope: :title, message: "Band already has album name" }
    validates :band_id, :title, :album_type, :year, presence: true

    belongs_to :band,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: 'Band'
end

W7D3/MovieApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        @bands = Band.all
        render :new
    end

    def create
        @bands = Band.all
        @album = Album.new(album_params)
        if @album.save
            redirect_to band_url(@album.band_id)
        else
            flash[:errors] = @album.errors.full_messages
            redirect_to new_band_album_url(@album.band_id)
        end
    end

    def show
        @album = Album.find_by(id: params[:id])
        render :show
    end

    def edit
        @bands = Band.all
        @album = Album.find_by(id: params[:id])
        render :edit
    end

    def update
        @album = Album.find_by(id: params[:id])
        if @album.update_attributes(album_params)
            redirect_to album_url(@album.id)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit, status: 422
        end
    end

    def destroy
        @album = Album.find_by(id: params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end

    private

    def album_params
        params
            .require(:album)
            .permit(:band_id, :title, :album_type, :year)
    end
end

W7D3/MovieApp/app/views/albums/edit.html.erb
<h2>Edit Your Album!</h2>
<br />
<form action="<%= album_url(@album.id) %>" method="post">
    <input type="hidden" name="_method" value="patch"/>
    <%= auth_token %>
    <label for="band"><b>Album Creator:</b></label>
    <select name="album[band_id]" id="band">
        <% @bands.each do |band| %>
            <option value="<%= band.id %>" <% @album.band_id == band.id ? "selected" : "" %>><%= band.name %></option>
        <% end %>
    </select>
    <br />
    <br />

    <label for="title"><b>Your Album Title:</b></label>
    <input type="text" id="title" name="album[title]" value="<%= @album.title %>"/>
    <br />
    <br />

    <label for="year"><b>Album Year:</b></label>
    <input type="text" id="year" name="album[year]" value="<%= @album.year %>"/>
    <br />
    <br />

    <b>Album Type:</b>
    <label for="album_type">Live</label>
    <input type="radio" name="album[album_type]" id="album_type" value="Live" <%= @album.album_type == "Live" ? 'checked' : '' %>/>

    <label for="album_type2">Studio</label>
    <input type="radio" name="album[album_type]" id="album_type2" value="Studio" <%= @album.album_type == "Studio" ? 'checked' : '' %>/>
    <br />
    <br />
    <input type="submit" value="Update Your Album"/>

</form>

W7D3/MovieApp/app/views/albums/new.html.erb
<h2>Make Your New Album!</h2>
<br />
<form action="<%= albums_url %>" method="post">
    <%= auth_token %>
    <label for="band"><b>Album Creator:</b></label>
    <select name="album[band_id]" id="band">
            <option disabled selected> Please Select
        <% @bands.each do |band| %>
            <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
    </select>
    <br />
    <br />

    <label for="title"><b>Your Album Title:</b></label>
    <input type="text" id="title" name="album[title]"/>
    <br />
    <br />

    <label for="year"><b>Album Year:</b></label>
    <input type="text" id="year" name="album[year]"/>
    <br />
    <br />

    <b>Album Type:</b>
    <label for="album_type">Live</label>
    <input type="radio" name="album[album_type]" id="album_type" value="Live"/>

    <label for="album_type2">Studio</label>
    <input type="radio" name="album[album_type]" id="album_type2" value="Studio"/>
    <br />
    <br />
    <input type="submit" value="Create Your Album"/>

</form>

W7D3/MovieApp/app/views/albums/show.html.erb
<br />
<form action="<%= album_url(@album.id) %>" method="post">
    <input="hidden" name="_method" value="delete"/>
    <%= auth_token %>

    <input type="submit" value="Delete this Album"/>
</form>
<br />
<br />

<style> 
    table td {
        border: solid black 1px;
    }
    thead, tfoot {
        background-color: aqua;
    }
</style>
<table>
    <thead> 
        <tr>
        <th colspan='5'> <%= @album.title %> </tr>
    </thead>
    <tbody>
        <td> Band_Id:  </td>
        <td> <%= @album.band_id %></td>
    </tbody>
    <tbody>
        <td> Year:  </td>
        <td> <%= @album.year %></td>
    </tbody>
</table>
<br />

<a href="<%= edit_album_url(@album.id) %>">Edit Album</a>

<br />
<br />
<a href="<%= band_url(@album.band_id) %>">Back to Band Page</a>